
export const allEmloyeeData = [
  {
    name: "akash biswas",
    email: "akashrahul2006@gmail.com",
    password: 1806404791,
    dashboard: { new: 2, accept: 3, complete: 4, failed: 1 },
    task: [
      {
        createdDate: "22 Oct 2024",
        id: 2341,
        teskTitle: "Make a Blog Application",
        taskDescription:
          "Make a full stack blog application with responsive design, more functionality, animations, user interaction, dynamic values, complex backend, and a beautiful landing page with authentication.",
        complitated: true,
        failed: 0,
        active: 2,
        color: "red",
        colorNumber: 500,
        role: "developed",
      },
      {
        createdDate: "18 Oct 2024",
        id: 2442,
        teskTitle: "Create E-commerce Website",
        taskDescription:
          "Develop an e-commerce website with product listings, payment gateway integration, cart functionality, and order tracking. Ensure user-friendly UI and mobile responsiveness.",
        complitated: false,
        failed: 1,
        active: 4,
        color: "green",
        colorNumber: 500,
        role: "E-com",
      },
      {
        createdDate: "12 Oct 2024",
        id: 2343,
        teskTitle: "Build Portfolio Website",
        taskDescription:
          "Design and develop a personal portfolio website with interactive sections, a blog, and project showcase. Ensure responsiveness and SEO optimization.",
        complitated: true,
        failed: 0,
        active: 0,
        color: "blue",
        colorNumber: 500,
        role: "Build",
      },
      {
        createdDate: "10 Oct 2024",
        id: 2344,
        teskTitle: "Implement Chat Application",
        taskDescription:
          "Build a real-time chat application with WebSocket integration, multi-user support, message encryption, and responsive design. Ensure cross-browser compatibility.",
        complitated: false,
        failed: 1,
        active: 3,
        color: "yellow",
        colorNumber: 500,
        role: "Optimize",
      },
      {
        createdDate: "05 Oct 2024",
        id: 2345,
        teskTitle: "Develop Task Management App",
        taskDescription:
          "Create a task management app with features for task creation, prioritization, reminders, and progress tracking. Include a calendar view and notifications.",
        complitated: true,
        failed: 0,
        active: 1,
        color: "green",
        colorNumber: 500,
        role: "developed",
      },
    ],
  },
  {
    name: "rahul biswas",
    email: "akashrahul2610@gmail.com",
    password: 123456,
    dashboard: { new: 3, accept: 1, complete: 3, failed: 2 },
    task: [
      {
        createdDate: "42 Oct 2024",
        name: "Sukanta mondal",
        id: 2315,
        teskTitle: "Make a chat Application",
        taskDescription:
          "Make a full stack chat application with responsive design, more functionality, animations, user interaction, dynamic values, complex backend, and a beautiful landing page with authentication.",
        complitated: true,
        failed: 0,
        active: 2,
        color: "green",
        colorNumber: 500,
        role: "developed",
      },
      {
        createdDate: "18 nov 2024",
        name: "Rahul singha",
        id: 2442,
        teskTitle: "Create dynamic Website",
        taskDescription:
          "Develop an e-commerce website with product listings, payment gateway integration, cart functionality, and order tracking. Ensure user-friendly UI and mobile responsiveness.",
        complitated: false,
        failed: 1,
        active: 4,
        color: "yellow",
        colorNumber: 500,
        role: "E-com",
      },
      {
        createdDate: "12 Oct 2024",
        name: "surya singha",
        id: 3264,
        teskTitle: "Build Portfolio Website",
        taskDescription:
          "Design and develop a personal portfolio website with interactive sections, a blog, and project showcase. Ensure responsiveness and SEO optimization.",
        complitated: false,
        failed: 0,
        active: 0,
        color: "red",
        colorNumber: 500,
        role: "developed",
      },
      {
        createdDate: "10 Oct 2024",
        name: "Ravi Kumar",
        id: 2344,
        teskTitle: "Implement Chat Application",
        taskDescription:
          "Build a real-time chat application with WebSocket integration, multi-user support, message encryption, and responsive design. Ensure cross-browser compatibility.",
        complitated: false,
        failed: 1,
        active: 3,
        color: "blue",
        colorNumber: 500,
        role: "Optimize",
      },
      {
        createdDate: "05 Oct 2024",
        name: "Neha Patel",
        id: 2345,
        teskTitle: "Develop Task Management App",
        taskDescription:
          "Create a task management app with features for task creation, prioritization, reminders, and progress tracking. Include a calendar view and notifications.",
        complitated: true,
        failed: 0,
        active: 1,
        color: "green",
        colorNumber: 500,
        role: "developed",
      },
    ],
  },
];
export const adminData = [
  {
    name: "akash biswas",
    email: "akashadmin@gmail.com",
    password:"admin akash",
  },
];
